import { Geist, Geist_Mono, BBH_Bogle } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css"

const bogle = BBH_Bogle({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pencil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="cupcake">
        <body className={`${bogle.className} tracking-wider`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
